
Due to MODULEPATH changes, the following have been reloaded:
  1) openmpi/2.1.1

Python 3.5.4
Using TensorFlow backend.
Traceback (most recent call last):
  File "./modelVariance.py", line 90, in <module>
    args.modelName)
  File "./modelVariance.py", line 50, in main_driver
    raise Exception(modelDir)
Exception: []
